// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYg35X-5ocVDYFNSZuH5IoR_NVeUIBcuc',
    appId: '1:447187951174:web:c6044dd0b05f7477f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    authDomain: 'ydapp-830fe.firebaseapp.com',
    storageBucket: 'ydapp-830fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6cONKgiSYXLaVSU0pABzO-vPQ5_4zX0',
    appId: '1:447187951174:android:8f4a43b5257dba6ff9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtYC4xI3m5ZCle-HYLbOXrbjNzsfh46I',
    appId: '1:447187951174:ios:91f48f6e25a7aba5f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
    iosBundleId: 'com.example.ydtind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtYC4xI3m5ZCle-HYLbOXrbjNzsfh46I',
    appId: '1:447187951174:ios:91f48f6e25a7aba5f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
    iosBundleId: 'com.example.ydtind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYg35X-5ocVDYFNSZuH5IoR_NVeUIBcuc',
    appId: '1:447187951174:web:5c14c5a34116b3d2f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    authDomain: 'ydapp-830fe.firebaseapp.com',
    storageBucket: 'ydapp-830fe.appspot.com',
  );

}