// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:yiddishconnect/utils/firebase_remote_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseRemoteConfigHelper.instance
        .getString("apiKey_FirebaseOptions_web"), //api key in firebase
    appId: '1:447187951174:web:87f8416583c6a578f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    authDomain: 'ydapp-830fe.firebaseapp.com',
    storageBucket: 'ydapp-830fe.appspot.com',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseRemoteConfigHelper.instance
        .getString("apiKey_FirebaseOptions_android"), //api key in firebase
    appId: '1:447187951174:android:61d56137bbc9eb00f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseRemoteConfigHelper.instance
        .getString("apiKey_FirebaseOptions_ios"), //api key in firebase
    appId: '1:447187951174:ios:c1f9145802338ff7f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
    iosClientId:
        '447187951174-isl6gichoftovpct8jcpcahddfdujd00.apps.googleusercontent.com',
    iosBundleId: 'com.yiddishland.yiddishconnect',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseRemoteConfigHelper.instance
        .getString("apiKey_FirebaseOptions_mac"), //api key in firebase
    appId: '1:447187951174:ios:c1f9145802338ff7f9b447',
    messagingSenderId: '447187951174',
    projectId: 'ydapp-830fe',
    storageBucket: 'ydapp-830fe.appspot.com',
    iosClientId:
        '447187951174-isl6gichoftovpct8jcpcahddfdujd00.apps.googleusercontent.com',
    iosBundleId: 'com.yiddishland.yiddishconnect',
  );
}
