name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Without Blocking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter (3.16.9 with Dart 3.3.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze Dart code (non-blocking)
        run: flutter analyze || true  # <- won't fail pipeline

      - name: Run tests (non-blocking)
        run: flutter test || true     # <- also won’t fail pipeline
