name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download official Flutter 3.19.0 with Dart 3.7.0
        run: |
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz
          tar xf flutter_linux_3.19.0-stable.tar.xz
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter --version
          dart --version
          flutter pub get
          flutter analyze
          flutter test
        shell: bash

