name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Check (Relaxed)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter (3.16.9)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze (show issues, don’t fail)
        run: flutter analyze
        continue-on-error: true

      - name: Test (show failures, don’t block)
        run: flutter test
        continue-on-error: true
